/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;
import java.util.Vector;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import logica.Libreria;
import logica.Libro;
/**
 *
 * @author HLEAL
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private Libreria libreria;
    private DefaultTableModel modelo;
    
    public VentanaPrincipal() {
        Vector columnNames = new Vector();
        columnNames.add("Codigo");columnNames.add("Titulo");columnNames.add("Tipo");columnNames.add("Numero de páginas");columnNames.add("Precio");
        this.modelo = new DefaultTableModel(columnNames, 0);
        
        initComponents();
        
        libreria = new Libreria();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.btnGroupConsultarLibreria.add(this.rbtnCodigo);
        this.btnGroupConsultarLibreria.add(this.rbtnTitulo);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupConsultarLibreria = new javax.swing.ButtonGroup();
        panelLibreria = new javax.swing.JPanel();
        panelAgregarNuevoLibro = new javax.swing.JPanel();
        lblCodigo = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        lblTipo = new javax.swing.JLabel();
        lblNumeroDePaginas = new javax.swing.JLabel();
        txtNumeroDePaginas = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtTipo = new javax.swing.JTextField();
        txtCodigo = new javax.swing.JTextField();
        btnAgregarLibro = new javax.swing.JButton();
        panelCatalogo = new javax.swing.JPanel();
        panelConsultarLibreria = new javax.swing.JPanel();
        lblBuscar = new javax.swing.JLabel();
        txtBuscar = new javax.swing.JTextField();
        rbtnTitulo = new javax.swing.JRadioButton();
        rbtnCodigo = new javax.swing.JRadioButton();
        btnBuscarConsulta = new javax.swing.JButton();
        panelListarLibros = new javax.swing.JPanel();
        lblTipoLibro = new javax.swing.JLabel();
        cmbTipo = new javax.swing.JComboBox<>();
        btnBuscarListar = new javax.swing.JButton();
        lblCantidadDeLibros = new javax.swing.JLabel();
        lblCantidadActualDeLibros = new javax.swing.JLabel();
        panelResultados = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblResultados = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Libreria Unicartagena");
        setBackground(new java.awt.Color(255, 255, 255));

        panelLibreria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Librería", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        panelLibreria.setToolTipText("");

        panelAgregarNuevoLibro.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Agregar nuevo libro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelAgregarNuevoLibro.setToolTipText("");

        lblCodigo.setText("Código:");

        lblTitulo.setText("Título:");

        lblTipo.setText("Tipo:");

        lblNumeroDePaginas.setText("Numero de Páginas:");

        txtNumeroDePaginas.setToolTipText("Ingresar el numero de páginas.");
        txtNumeroDePaginas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumeroDePaginasKeyTyped(evt);
            }
        });

        txtTitulo.setToolTipText("Ingresar título del libro.");

        txtTipo.setToolTipText("Ingresar el tipo de libro.");
        txtTipo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTipoKeyTyped(evt);
            }
        });

        txtCodigo.setToolTipText("Ingresar código del libro. No deb estar registrado con anterioridad.");
        txtCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCodigoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCodigoKeyTyped(evt);
            }
        });

        btnAgregarLibro.setText("Agregar Libro");
        btnAgregarLibro.setToolTipText("Agregar el libro al catálogo de la librería.");
        btnAgregarLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAgregarNuevoLibroLayout = new javax.swing.GroupLayout(panelAgregarNuevoLibro);
        panelAgregarNuevoLibro.setLayout(panelAgregarNuevoLibroLayout);
        panelAgregarNuevoLibroLayout.setHorizontalGroup(
            panelAgregarNuevoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarNuevoLibroLayout.createSequentialGroup()
                .addGroup(panelAgregarNuevoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAgregarNuevoLibroLayout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addGroup(panelAgregarNuevoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblNumeroDePaginas)
                            .addComponent(lblTipo)
                            .addComponent(lblTitulo)
                            .addComponent(lblCodigo))
                        .addGap(18, 18, 18)
                        .addGroup(panelAgregarNuevoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNumeroDePaginas, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelAgregarNuevoLibroLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(btnAgregarLibro)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelAgregarNuevoLibroLayout.setVerticalGroup(
            panelAgregarNuevoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAgregarNuevoLibroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelAgregarNuevoLibroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panelAgregarNuevoLibroLayout.createSequentialGroup()
                        .addComponent(lblCodigo)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitulo)
                        .addGap(18, 18, 18)
                        .addComponent(lblTipo)
                        .addGap(18, 18, 18)
                        .addComponent(lblNumeroDePaginas))
                    .addGroup(panelAgregarNuevoLibroLayout.createSequentialGroup()
                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumeroDePaginas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(40, 40, 40)
                .addComponent(btnAgregarLibro)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        panelCatalogo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Catálogo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelCatalogo.setToolTipText("");

        panelConsultarLibreria.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Consultar Catálogo", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblBuscar.setText("Buscar:");
        lblBuscar.setToolTipText("Buscar libro por titulo o código");

        txtBuscar.setToolTipText("Ingresar propiedad para buscar el libro.");
        txtBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuscarActionPerformed(evt);
            }
        });

        rbtnTitulo.setText("Titulo");

        rbtnCodigo.setText("Codigo");

        btnBuscarConsulta.setText("Buscar");
        btnBuscarConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarConsultaMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelConsultarLibreriaLayout = new javax.swing.GroupLayout(panelConsultarLibreria);
        panelConsultarLibreria.setLayout(panelConsultarLibreriaLayout);
        panelConsultarLibreriaLayout.setHorizontalGroup(
            panelConsultarLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarLibreriaLayout.createSequentialGroup()
                .addGroup(panelConsultarLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelConsultarLibreriaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBuscar)
                        .addGap(18, 18, 18)
                        .addGroup(panelConsultarLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelConsultarLibreriaLayout.createSequentialGroup()
                                .addComponent(rbtnTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(rbtnCodigo))
                            .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelConsultarLibreriaLayout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(btnBuscarConsulta)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        panelConsultarLibreriaLayout.setVerticalGroup(
            panelConsultarLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsultarLibreriaLayout.createSequentialGroup()
                .addGroup(panelConsultarLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBuscar)
                    .addComponent(txtBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelConsultarLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtnTitulo)
                    .addComponent(rbtnCodigo))
                .addGap(18, 18, 18)
                .addComponent(btnBuscarConsulta)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        panelListarLibros.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Listar Libros", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        lblTipoLibro.setText("Tipo:");
        lblTipoLibro.setToolTipText("Listar libros por el tipo.");

        cmbTipo.setMaximumRowCount(4);
        cmbTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "Cualquier otro" }));
        cmbTipo.setToolTipText("Seleccionar el tipo de libro");

        btnBuscarListar.setText("Buscar");
        btnBuscarListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarListarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelListarLibrosLayout = new javax.swing.GroupLayout(panelListarLibros);
        panelListarLibros.setLayout(panelListarLibrosLayout);
        panelListarLibrosLayout.setHorizontalGroup(
            panelListarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarLibrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTipoLibro)
                .addGap(40, 40, 40)
                .addGroup(panelListarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarListar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        panelListarLibrosLayout.setVerticalGroup(
            panelListarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelListarLibrosLayout.createSequentialGroup()
                .addGroup(panelListarLibrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cmbTipo)
                    .addComponent(lblTipoLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBuscarListar)
                .addGap(24, 24, 24))
        );

        lblCantidadDeLibros.setText("Cantidad de Libros: ");

        lblCantidadActualDeLibros.setText("0/150");

        javax.swing.GroupLayout panelCatalogoLayout = new javax.swing.GroupLayout(panelCatalogo);
        panelCatalogo.setLayout(panelCatalogoLayout);
        panelCatalogoLayout.setHorizontalGroup(
            panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCatalogoLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(panelConsultarLibreria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelListarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(panelCatalogoLayout.createSequentialGroup()
                .addGap(289, 289, 289)
                .addComponent(lblCantidadDeLibros)
                .addGap(25, 25, 25)
                .addComponent(lblCantidadActualDeLibros)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCatalogoLayout.setVerticalGroup(
            panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCatalogoLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCantidadDeLibros)
                    .addComponent(lblCantidadActualDeLibros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelCatalogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelConsultarLibreria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelListarLibros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panelResultados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Resultados", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        panelResultados.setToolTipText("");

        tblResultados.setAutoCreateRowSorter(true);
        tblResultados.setModel(this.modelo);
        tblResultados.setToolTipText("");
        jScrollPane1.setViewportView(tblResultados);

        javax.swing.GroupLayout panelResultadosLayout = new javax.swing.GroupLayout(panelResultados);
        panelResultados.setLayout(panelResultadosLayout);
        panelResultadosLayout.setHorizontalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        panelResultadosLayout.setVerticalGroup(
            panelResultadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelResultadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelLibreriaLayout = new javax.swing.GroupLayout(panelLibreria);
        panelLibreria.setLayout(panelLibreriaLayout);
        panelLibreriaLayout.setHorizontalGroup(
            panelLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibreriaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelLibreriaLayout.createSequentialGroup()
                        .addComponent(panelAgregarNuevoLibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelLibreriaLayout.setVerticalGroup(
            panelLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLibreriaLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(panelLibreriaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(panelAgregarNuevoLibro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCatalogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(panelResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLibreria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelLibreria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarLibroActionPerformed
        if(txtCodigo.getText().equals("") ||
                txtTitulo.getText().equals("") ||
                txtTipo.getText().equals("") ||
                txtNumeroDePaginas.getText().equals("")){
            return;
        }
        
        int codigo = Integer.parseInt(txtCodigo.getText());
        String titulo = txtTitulo.getText();
        int tipo = Integer.parseInt(txtTipo.getText());
        int numeroPaginas = Integer.parseInt(txtNumeroDePaginas.getText());
        
        Libro libro = new Libro(titulo, codigo, numeroPaginas, tipo);
        if(libreria.agregarLibro(libro)){
            JOptionPane.showMessageDialog(null, "Se logró agregar con exito el nuevo libro.", "Agregar nuevo libro.", JOptionPane.INFORMATION_MESSAGE);
            txtCodigo.setText("");
            txtTitulo.setText("");
            txtTipo.setText("");
            txtNumeroDePaginas.setText("");
            this.lblCantidadActualDeLibros.setText(libreria.getIndiceActual()+ "/150");
        }
        else{
            JOptionPane.showMessageDialog(null, "No se pudo agregar el libro, código de libro ya repetido.", "Agregar nuevo libro.", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnAgregarLibroActionPerformed

    private void txtCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyReleased
                 
    }//GEN-LAST:event_txtCodigoKeyReleased

    private void txtCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCodigoKeyTyped
        comprobarTextoNumero(evt);
    }//GEN-LAST:event_txtCodigoKeyTyped

    private void txtTipoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTipoKeyTyped
        // TODO add your handling code here:
        comprobarTextoNumero(evt);
    }//GEN-LAST:event_txtTipoKeyTyped

    private void txtNumeroDePaginasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumeroDePaginasKeyTyped
        // TODO add your handling code here:
        comprobarTextoNumero(evt);
    }//GEN-LAST:event_txtNumeroDePaginasKeyTyped

    private void txtBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuscarActionPerformed

    private void btnBuscarConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarConsultaMouseClicked
        if(this.modelo.getRowCount() >= 0){
            System.out.println("Filas por borrar: " + modelo.getRowCount());
//            for (int i = 0; i < modelo.getRowCount(); i++) {
//                System.out.println("Se ha borrado la fila: " + i);
//                this.modelo.removeRow(i);
//            }
            this.modelo.setRowCount(0);
        }
        String titulo;
        int codigo;
        Libro[] libros;
        Libro libro;

        if(this.rbtnTitulo.isSelected()){
            titulo = this.txtBuscar.getText();
            libros = libreria.buscarLibro(titulo);
            for (int i = 0; i < libros.length && libros[i] != null; i++) {
                this.modelo.addRow(new Object[]{libros[i].getCodigo(), libros[i].getTitulo(), libros[i].getTipo(), libros[i].getNumeroPaginas(), libreria.calcularPrecio(libros[i])});
            }
        }
        else{
            codigo = Integer.parseInt(this.txtBuscar.getText());
            libro = libreria.buscarLibro(codigo);
            this.modelo.addRow(new Object[]{libro.getCodigo(), libro.getTitulo(), libro.getTipo(), libro.getNumeroPaginas(), libreria.calcularPrecio(libro)});
        }
    }//GEN-LAST:event_btnBuscarConsultaMouseClicked

    private void btnBuscarListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarListarActionPerformed
        String item = (String)this.cmbTipo.getSelectedItem();
        Libro[] libros;
        
        if(item.equals("1")){
            libros = libreria.listarLibrosTipo(1);
        }else if(item.equals("2")){
            libros = libreria.listarLibrosTipo(2);
        }else if(item.equals("3")){
            libros = libreria.listarLibrosTipo(3);
        }else{
            libros = libreria.listarLibrosTipo(5);
        }
        
        if(this.modelo.getRowCount() > 0){
//            for (int i = 0; i < modelo.getRowCount(); i++) {
//                this.modelo.removeRow(i);
//            }
            this.modelo.setRowCount(0);
        }
        
        for (int i = 0; i < libros.length && libros[i] != null; i++) {
                this.modelo.addRow(new Object[]{libros[i].getCodigo(), libros[i].getTitulo(), libros[i].getTipo(), libros[i].getNumeroPaginas(), libreria.calcularPrecio(libros[i])});
        }
    }//GEN-LAST:event_btnBuscarListarActionPerformed
    
    private void comprobarTextoNumero(java.awt.event.KeyEvent evt){
        char caracter;        
        caracter = evt.getKeyChar();
        if(!Character.isDigit(caracter)){
            evt.consume();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregarLibro;
    private javax.swing.JButton btnBuscarConsulta;
    private javax.swing.JButton btnBuscarListar;
    private javax.swing.ButtonGroup btnGroupConsultarLibreria;
    private javax.swing.JComboBox<String> cmbTipo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBuscar;
    private javax.swing.JLabel lblCantidadActualDeLibros;
    private javax.swing.JLabel lblCantidadDeLibros;
    private javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblNumeroDePaginas;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JLabel lblTipoLibro;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel panelAgregarNuevoLibro;
    private javax.swing.JPanel panelCatalogo;
    private javax.swing.JPanel panelConsultarLibreria;
    private javax.swing.JPanel panelLibreria;
    private javax.swing.JPanel panelListarLibros;
    private javax.swing.JPanel panelResultados;
    private javax.swing.JRadioButton rbtnCodigo;
    private javax.swing.JRadioButton rbtnTitulo;
    private javax.swing.JTable tblResultados;
    private javax.swing.JTextField txtBuscar;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtNumeroDePaginas;
    private javax.swing.JTextField txtTipo;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
